name: GitHub Pages

on:
  push:
    branches:
      - master    # change if your default branch is different (e.g. master)

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Ruby (for Jekyll)
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1

      - name: Install Jekyll and Bundler
        run: |
          gem install bundler jekyll

      - name: Build site
        working-directory: ./docs
        run: |
          jekyll build --destination ../site

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
